### ISSUE TITLE
Item Right Swipe click on button "Done" to swipe back

### ISSUE THREAD

**Issue by khmergeo** [brookshi/LLMListView#12]
I have create new button "Done" and "Delete" on ItemRightTemplate.
I want to click Done button to swipe back after I edit on this item ready.

Can you help me please ?

**Comment by brookshi** [comment]
Ok. I will add a sample for this function, please wait a moment

**Comment by brookshi** [comment]
I add two method : ResetSwipe & ResetSwipeWithAnimation. You can checkout the code and try the FixedSwipePage in sample.
If it meets your requirement, please let me know, I will publish it to Nuget.

**Comment by f1nzer** [comment]
@brookshi  btw, I think it's will be a good feature to add "SwipedMemberPath" property to listview (like DisplayMemberPath and SelectedValuePath from another controls).

**Comment by brookshi** [comment]
@F1nZeR , Is "SwipedMemberPath" used to determine the SwipeMode for ListViewItem?

**Comment by f1nzer** [comment]
@brookshi we need this in order to track current swipe state of every ListViewItem.
For example:

``` cs
class ViewModel
{
    public bool IsSwiped { get; set; }
}
```

And then we can:

``` xaml
<LLMListView IsSwipedMemberPath='IsSwiped' />
```

In this case we would have ability to use MVVM approach. (only when SwipeMode="Fix" I guess)

**Comment by brookshi** [comment]
@F1nZeR , Good idea, But why not use this to control SwipeMode for each ListViewItem directly,
Just like:

``` C#
class ViewModel
{
    public SwipeMode SwipeMode { get; set; }
}

<LLMListView SwipeModeMemberPath='SwipeMode' />
```

SwipeMode.None and SwipeMode.Fix can cover your requirement.

**Comment by f1nzer** [comment]
@brookshi I don't think that it's good idea because it is a direct dependency to this control library (for example I'm using PCL targeting 3 different platforms).
In my opinion in most cases it's will be enough to provide bool property for this purpose (even SwipeMode enum in your example contains just 2 values :smile: ). Also it will cover needs of khmergeo: he can also change IsSwiped property (on viewModel) to false when needed.

**Comment by brookshi** [comment]
OK. I agree with you. I will try to add it this weekend :smiley: .

**Comment by brookshi** [comment]
@F1nZeR  I had implemented this function, cheers :beer:

**Comment by khmergeo** [comment]
Thank you all beloved brothers, 
Now I can do it with your issue.
