### ISSUE TITLE
Is there anyway to bind a mvvm item property to enable/disable the item right swipe?

### ISSUE THREAD

**Issue by jennifer-leung** [brookshi/LLMListView#14]

**Comment by brookshi** [comment]
Not support yet. You can try this way - #4 .

**Comment by jennifer-leung** [comment]
ok, thx!  Would you have any idea when it will be available?

**Comment by brookshi** [comment]
I will try to add this function tonight :smile: .

**Comment by jennifer-leung** [comment]
Thank you :)!

**Comment by brookshi** [comment]
Code had been pushed, please checkout the latest code and see the sample page "NormalFixPage".
Any question please let me know. thx!
If don't have any question, I will publish to Nuget tomorrow.
