### ISSUE TITLE
Performance Issue with 200 contacts loaded?

### ISSUE THREAD

**Issue by jennifer-leung** [brookshi/LLMListView#15]
Hi,

I am trying to load 200 contacts on the Normal Fix Swipe With Dynamic Template sample and when its scroll quickly the listitem goes dark grey, any idea why?

Kind Regards
Jennifer

**Comment by brookshi** [comment]
I think the grey color is background color of ListViewItem's placeholder, you can try to set `ShowsScrollingPlaceholders=False` for ListView to ignore it.

**Comment by jennifer-leung** [comment]
That's great it works however is there anyway to use x:Bind and x:Phrase to load the content first before the swipe templates?  As the listview scroll quickly, it show blank items.

**Comment by brookshi** [comment]
I don't think it's LLMListView's problem. The origin ListView may have the same problem.

**Comment by jennifer-leung** [comment]
ok, thank you for looking into this.
