### ISSUE TITLE
I can't set ItemContainerStyle

### ISSUE THREAD

**Issue by stefv** [brookshi/LLMListView#16]
Hi,

I tried to set the ItemContainerStyle property with this style:

```
<Style x:Key="ItemContainerStyle" TargetType="llm:LLMListViewItem">
            <Setter Property="Template">
                <Setter.Value>
                    <ControlTemplate TargetType="llm:LLMListViewItem">
                        <ListViewItemPresenter 
                            ContentTransitions="{TemplateBinding ContentTransitions}"
          SelectionCheckMarkVisualEnabled="True"
          CheckBrush="{ThemeResource SystemControlForegroundBaseMediumHighBrush}"
          CheckBoxBrush="{ThemeResource SystemControlForegroundBaseMediumHighBrush}"
          DragBackground="{ThemeResource ListViewItemDragBackgroundThemeBrush}"
          DragForeground="{ThemeResource ListViewItemDragForegroundThemeBrush}"
          FocusBorderBrush="{ThemeResource SystemControlForegroundAltHighBrush}"
          FocusSecondaryBorderBrush="{ThemeResource SystemControlForegroundBaseHighBrush}"
          PlaceholderBackground="{ThemeResource ListViewItemPlaceholderBackgroundThemeBrush}"
          PointerOverBackground="{ThemeResource SystemControlHighlightListLowBrush}"
          PointerOverForeground="{ThemeResource SystemControlHighlightAltBaseHighBrush}"
          SelectedBackground="{ThemeResource SystemControlHighlightListAccentLowBrush}"
          SelectedForeground="{ThemeResource SystemControlHighlightAltBaseHighBrush}"
          SelectedPointerOverBackground="{ThemeResource SystemControlHighlightListAccentMediumBrush}"
          PressedBackground="{ThemeResource SystemControlHighlightListMediumBrush}"
          SelectedPressedBackground="{ThemeResource SystemControlHighlightListAccentHighBrush}"
          DisabledOpacity="{ThemeResource ListViewItemDisabledThemeOpacity}"
          DragOpacity="{ThemeResource ListViewItemDragThemeOpacity}"
          ReorderHintOffset="{ThemeResource ListViewItemReorderHintThemeOffset}"
          HorizontalContentAlignment="{TemplateBinding HorizontalContentAlignment}"
          VerticalContentAlignment="{TemplateBinding VerticalContentAlignment}"
          ContentMargin="{TemplateBinding Padding}"
          CheckMode="Inline"/>
                    </ControlTemplate>
                </Setter.Value>
            </Setter>
            <Setter Property="HorizontalContentAlignment" Value="Stretch" />
        </Style>
```

This is working for ListView. But with LLMListView, when the application is starting I have this error:
Message = "System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at LLM.LLMListViewItem.ResetSwipe()"

I'm using the last version of the control from nuget: 0.1.5.

Stef

**Comment by brookshi** [comment]
Hi Stef,
I think it caused by this code `<ControlTemplate TargetType="llm:LLMListViewItem">`, it will replace LLMListViewItem's control template style.

**Comment by stefv** [comment]
Ok. Is there a solution to add a border between each item ? I searched in the source code but except to do a copy/paste of the style, I have the feeling it's complicated but I'm not an expert with XAML :(

Edit: sorry. I found the solution. I just setted BorderTickness on the style for LLMListViewItem. It's enough for what I need.

**Comment by brookshi** [comment]
:smile: Also you can add a bottom line in your ItemTemplate

**Comment by stefv** [comment]
It's what I started to do but I think because of the padding (0,12,0,12) in the LLMListViewItem, I had the padding on the left and on the right if my memory is good.
I wanted also to use ListViewItemPresenter to set the background colors like I wanted. But it's ok, I will see that later, it's not the most important.

Thank you.

**Comment by brookshi** [comment]
Hope [this project](https://github.com/brookshi/UWP_ZhiHuRiBao/blob/master/UWP_ZhiHuRiBao/Pages/MainPage.xaml#L246) can help you.
