### ISSUE TITLE
LLMListView is creating self header?

### ISSUE THREAD

**Issue by ghost** [brookshi/LLMListView#18]
I have a this code

`<swipe:LLMListView x:Name="product_list_content" Grid.Row="2" 
                          IsItemClickEnabled="True"
                          ItemLeftSwipeMode="None"
                          ItemRightActionRateForSwipeLength="0.5"
                          ItemRightSwipeMaxLength="135"
                          ItemRightSwipeMode="Fix"
                          DataContext="{StaticResource OrderViewModel}"
                          ItemsSource="{Binding}"
                          SelectionMode="Single">
                    <swipe:LLMListView.ItemTemplate>
                        <DataTemplate>
                            <Grid>
                                <Grid.ColumnDefinitions>
                                    <ColumnDefinition Width="200" />
                                    <ColumnDefinition Width="*" />
                                    <ColumnDefinition Width="*" />
                                    <ColumnDefinition Width="*" />
                                </Grid.ColumnDefinitions>
                                <TextBlock Grid.Column="0" Text="{Binding Item_name}" HorizontalAlignment="Left" VerticalAlignment="Center" FontSize="20" />
                                <TextBlock Text="{Binding quantity}" HorizontalAlignment="Left" VerticalAlignment="Center" FontSize="20" Grid.ColumnSpan="2" Margin="196,0,0,0"/>
                                <TextBlock Grid.Column="2" Text="{Binding discount}" HorizontalAlignment="Left" VerticalAlignment="Center" FontSize="20"/>
                                <TextBlock Grid.Column="3" Text="{Binding sell_price}" HorizontalAlignment="Left" VerticalAlignment="Center" FontSize="20"/>
                            </Grid>
                        </DataTemplate>
                    </swipe:LLMListView.ItemTemplate>
                </swipe:LLMListView>`

I can compile it successfully now my problem is
WHEN IT IS FROM COLLAPSE STATE WHEN I SHOW IT, IT CREATES ITS OWN HEADER, AN EMPTY HEADER 
![image](https://cloud.githubusercontent.com/assets/15153018/19513988/8f38eaa0-9624-11e6-9e25-030435cf7460.png)

THE YELLOW ONE IS THE HEADER.
hOW CAN i REMOVE THAT ITS ANNOYING.

**Comment by brookshi** [comment]
I think it's not header, it should be progress bar for pulling to refresh.
It should be hidden in normal case for its negative margin. 
Or InitScrollViewEventsForPullToRefresh function is not called may cause this problem.

```
private void InitScrollViewEventsForPullToRefresh()
        {
            if (CanPullToRefresh && Utils.IsOnMobile)
            {
                _scrollViewer.ViewChanging += ScrollViewer_ViewChanging;
                _scrollViewer.Margin = new Thickness(0, 0, 0, -RefreshAreaHeight);
                _scrollViewer.RenderTransform = new CompositeTransform() { TranslateY = -RefreshAreaHeight };
            }
        }
```

you can clone the source code and debug. pay attention to OnApplyTemplate and InitVisualState

**Comment by ghost** [comment]
Wow.... Great..

Do you have template for swiping the items from the top/bottom instead of left and right?

**Comment by brookshi** [comment]
Sorry, LLMListView doesn't support top/bottom swiping, it may has conflict with listview scrolling :smile:

**Comment by ghost** [comment]
Ahhh...

I found another issue. This:
![image](https://cloud.githubusercontent.com/assets/15153018/19587820/d479e3d8-9793-11e6-91d1-55f4f1b28fc2.png)

The buttons....
what possibly can cause that problem? Is it my layout?

**Comment by brookshi** [comment]
It may be caused by the button's height.
Seem height is different between the button with label and the button without label
