### ISSUE TITLE
Changing the background color of the item when selected 

### ISSUE THREAD

**Issue by ghost** [brookshi/LLMListView#19]
Hi here I am again. I found another issue on changing items background using blend gets an error. 

How can I change items background when selected? 

Is it supported in visual studio's blend?

Any response is a big help.

**Comment by brookshi** [comment]
Hi,

Below is part of ListViewItem's control template code, **SystemControlHighlightListAccentLowBrush** is the background brush of selected item. you can replace it or change it in source code(LLMListView/Themes/Generic.xaml).

```
 <VisualState x:Name="Selected">
                                    <Storyboard>
                                        <DoubleAnimation Duration="0:0:0"
                                                         Storyboard.TargetName="MultiSelectCheck"
                                                         Storyboard.TargetProperty="Opacity"
                                                         To="1" />
                                        <DoubleAnimation Duration="0"
                                                         Storyboard.TargetName="BorderBackground"
                                                         Storyboard.TargetProperty="Opacity"
                                                         To="1" />
                                        <ObjectAnimationUsingKeyFrames Storyboard.TargetName="BorderBackground" Storyboard.TargetProperty="Fill">
                                            <DiscreteObjectKeyFrame KeyTime="0" Value="{ThemeResource SystemControlHighlightListAccentLowBrush}" />
                                        </ObjectAnimationUsingKeyFrames>
                                        <ObjectAnimationUsingKeyFrames Storyboard.TargetName="ContentPresenter" Storyboard.TargetProperty="Foreground">
                                            <DiscreteObjectKeyFrame KeyTime="0" Value="{ThemeResource SystemControlHighlightAltBaseHighBrush}" />
                                        </ObjectAnimationUsingKeyFrames>
                                        <PointerUpThemeAnimation Storyboard.TargetName="ContentPresenter" />
                                    </Storyboard>
                                </VisualState>
```

**Comment by ghost** [comment]
it was downloaded on NuGet... editing generic.xaml is not posible right? Do you have alternatives? 

BTW thank you for your reply :)... Much appreciated

**Comment by brookshi** [comment]
It's open source, you can clone the source code and do what you want :smile:
Anyway, you can use `App.Current.Resources["SystemControlHighlightListAccentLowBrush"] = new SolidColorBrush(Colors.Red);` in *.xaml.cs to replace SystemControlHighlightListAccentLowBrush style to set background color of selected item.
like this:
![test](https://cloud.githubusercontent.com/assets/13607728/20311480/e6a21d72-ab8a-11e6-853b-b3bc77a99ff2.png)

**Comment by ghost** [comment]
wow... you are really amazing... Thank you so much...
