### ISSUE TITLE
How to add Left side Fixed actions similar as Right side actions?

### ISSUE THREAD

**Issue by kinju4374** [brookshi/LLMListView#2]
I want to use Swipe with Fixed and multiple actions. But I want to show 3 options on Left and 3 options on Right. Is it possible to do with this LLMListView control?

**Comment by kinju4374** [comment]
I used same LeftSwipeMode and LeftTemplate to achieve my requirement. Thanks a lot for this good API.

**Comment by brookshi** [comment]
:+1:
