### ISSUE TITLE
ListView.ScrollToView() is not working

### ISSUE THREAD

**Issue by ghost** [brookshi/LLMListView#20]
Hello I have this new issue.. I have this bunch of snippets:
` void ScrollToLast()
        {
            var selectedIndex = product_list_content.Items.Count - 1;
            if (selectedIndex < 0)
                return;

            product_list_content.SelectedIndex = selectedIndex;
            product_list_content.UpdateLayout();

            product_list_content.ScrollIntoView(product_list_content.SelectedItem);
        }`
where: product_list_content is an LLMListView

which is I want to scroll to the last item on the list but I found it not working on LLMListView..

**Comment by brookshi** [comment]
refer: [http://stackoverflow.com/a/32559623/5793821](http://stackoverflow.com/a/32559623/5793821)

**Comment by ghost** [comment]
thanks
