### ISSUE TITLE
How to add alternate row style

### ISSUE THREAD

**Issue by sreeman44** [brookshi/LLMListView#21]
i am trying to add alternate row color but it i didn't find any way.please let me know how can i accomplish
this. i need list view like below attachment. 

And Another issue how to fix the headers at the time of scrolling. here is my xaml design.

Thanks in advance

![alternaterows](https://cloud.githubusercontent.com/assets/22466957/21522220/98138c2a-cd29-11e6-992c-301e83398bc6.PNG)

<ctrl:LLMListView x:Name="RequisitionListView" Grid.Row="1" 
                          CanPullToRefresh="True"
                          FloatButtonIcon="Refresh"
                          FloatButtonVisibility="Visible"
                          IsItemClickEnabled="False"                                              
                          ItemsSource="{Binding Requisitions,
                                                Mode=TwoWay}"                        
                                                
                         HorizontalAlignment="Stretch"  HorizontalContentAlignment="Stretch" MinWidth="600" Margin="0,10,0,0" ScrollViewer.VerticalScrollBarVisibility="Visible">
            <ctrl:LLMListView.ItemTemplate>
                <DataTemplate>
                    <Grid Name="grdTest" MinWidth="600">
                        <Grid.RowDefinitions>
                            <RowDefinition Height="*"  ></RowDefinition>
                        </Grid.RowDefinitions>
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition Width="6*" />
                            <ColumnDefinition Width="2*" />
                            <ColumnDefinition Width="2*" />
                        </Grid.ColumnDefinitions>
                        <Border Grid.Column="0" BorderBrush="Black" BorderThickness="0">
                            <TextBlock 
                           Margin="12,6,0,0"
                           Text="{Binding ZPOSITIONTITLE}" TextWrapping="Wrap" Style="{StaticResource ResourceKey=DashboardGridLabelStyle}"  />
                        </Border>
                        <Border Grid.Column="1" BorderBrush="Black" BorderThickness="0">
                            <TextBlock 
                           Margin="12,6,0,0"
                           Text="{Binding ZJOBREQUISITIONNUMBER}" TextWrapping="Wrap" Style="{StaticResource ResourceKey=DashboardGridLabelStyle}" >
                            </TextBlock>
                        </Border>
                        <Border Grid.Column="2" BorderBrush="Black" BorderThickness="0">
                            <RadioButton Name="radioSelect" GroupName="radioAction" IsChecked="{Binding Action,Mode=TwoWay}" Margin="30,0,0,0"></RadioButton>
                        </Border>
                    </Grid>
                </DataTemplate>
            </ctrl:LLMListView.ItemTemplate>
            <ListView.ItemContainerStyle>
                <Style TargetType="ListViewItem">
                    <Setter Property="HorizontalContentAlignment" Value="Stretch" />
                </Style>
            </ListView.ItemContainerStyle>
            <ListView.Header>
                <Style TargetType="ListViewHeaderItem">
                    <Setter Property="HorizontalContentAlignment" Value="Stretch"></Setter>
                </Style>
            </ListView.Header>
            <ListView.HeaderTemplate>
                <DataTemplate>
                    <Grid Height="50" Background="DarkGray">
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition Width="6*" />
                            <ColumnDefinition Width="2*" />
                            <ColumnDefinition Width="2*" />
                        </Grid.ColumnDefinitions>
                        <TextBlock x:Uid="tbTitle" Text="Position Title" Grid.Column="0"  Style="{StaticResource ResourceKey=DashboardGridHeaderStyle}" />
                        <TextBlock x:Uid="tbRequistion" Text="Requisition Number" Grid.Column="1" Style="{StaticResource ResourceKey=DashboardGridHeaderStyle}" />
                        <TextBlock x:Uid="tbName"  Text="Action" Grid.Column="2" Style="{StaticResource ResourceKey=DashboardGridHeaderStyle}" />
                    </Grid>
                </DataTemplate>
            </ListView.HeaderTemplate>
        </ctrl:LLMListView>

**Comment by brookshi** [comment]
I think DataTemplateSelector is a good suggestion for you.
https://blogs.msdn.microsoft.com/bryanbolling/2012/12/08/how-to-control-the-datatemplateselector-in-windows-store-apps/

**Comment by brookshi** [comment]
For fixed headers, you can add headers on the top of Listview or use grouped list view( group list view exist in demo)
