### ISSUE TITLE
In SwipeMode Fix ResetSwipe after clicking on Edit

### ISSUE THREAD

**Issue by slolam** [brookshi/LLMListView#23]
Hi,

I have Edit and Delete action buttons on left swipe, when I click on the Edit button the handler gets control however the item does not reset to normal. i.e. the Edit and Delete buttons still appear. Am I missing something here?

**Comment by brookshi** [comment]
Action 'reset' is controlled by yourself and there are two ways to rest it to normal.
1. MVVM mode, binding property like `IsSwipedLeft` of your model to `IsSwipedLeftMemberPath`, set it to false to reset it.
```C#
IsSwipedLeftMemberPath="IsSwipedLeft"
```
2. get focused LLMListViewItem and call `ResetSwipeWithAnimation()`;
```C#
 var item = Utils.FindVisualParent<LLMListViewItem>(sender as AppBarButton);
 item?.ResetSwipeWithAnimation();
```
You also can check the sample `NormalFixPage`.

**Comment by slolam** [comment]
Thanks, I would take a look at it and close this issue. I thought so that I was missing something there

**Comment by slolam** [comment]
Thanks
