### ISSUE TITLE
Selection Changed event.

### ISSUE THREAD

**Issue by kinju4374** [brookshi/LLMListView#3]
**SelectionChanged** event will also work even we have included swipe events right?

**Comment by brookshi** [comment]
No. But you can add "ItemSwipeProgressInTouch" event  for LLMListView and set selected item in this event.
such as:
in .xaml
**ItemSwipeProgressInTouch="MasterListView_ItemSwipeProgressInTouch"**

in .xaml.cs

**private void MasterListView_ItemSwipeProgressInTouch(object sender, SwipeProgressEventArgs args)
        {
            var item = sender as LLMListViewItem;
            if (item == null)
                return;
            if (!item.IsSelected)
                item.IsSelected = true;
        }**

**Comment by kinju4374** [comment]
Ok. 

Actually currently with native Listview I am using selection changed event to navigate to other page. 

Can you edit your code and let me know whether it is possible?

**Comment by brookshi** [comment]
O. o, Sorry, Maybe I Got it wrong. 
Yes, SelectionChanged event will also work. It should be navigate to other page if click listview item, also valid for LLMListView

**Comment by kinju4374** [comment]
Ok, Thanks

**Comment by kinju4374** [comment]
`<customLV:LLMListView Name="customListView"
                                          HorizontalContentAlignment="Stretch"
                                          Visibility="Collapsed"
                                          Grid.Row="1"
                                          ItemTemplate="{StaticResource MyListViewTemplate}"
                                          SelectionChanged="MyListView_SelectionChanged"/>`

When I am adding above code it is crashing. No displaying the UI. When I use your project then it works but when I use LLMListView using Nuget package it is crashing. Can you please suggest what am I doing wrong?

**Comment by brookshi** [comment]
Sorry for my mistake, when visibility is collapsed, LLMListView doesn't call OnApplyTemplate.it cause null exception. 
I have fixed it and update 0.0.18 to Nuget, you can update and retry.
Thanks.

**Comment by kinju4374** [comment]
Thanks for correcting it so quickly. I will try again and update you. Also, could you suggest is it possible to add fix swipe options dynamically?

**Comment by brookshi** [comment]
I think it's ok. You can test it.

**Comment by kinju4374** [comment]
Thanks it worked. But now I am facing another issue. When I use **ItemContainerStyle**. It is crashing. My ItemContainerStyle is 

`<Style x:Key="LLMGenericListViewContainerStyle"
           TargetType="customLV:LLMListViewItem">
        <Setter Property="HorizontalContentAlignment"
                Value="Stretch" />
        <Setter Property="Margin"
                Value="0"/>
        <Setter Property="Padding"
                Value="0"/>
        <Setter Property="Template">
            <Setter.Value>
                <ControlTemplate TargetType="customLV:LLMListViewItem">
                    <ListViewItemPresenter ContentMargin="0,0,0,1"
                                           Margin="0"/>
                </ControlTemplate>
            </Setter.Value>
        </Setter>
    </Style>`

Could you please suggest what I am doing wrong ? Also, please suggest can we add swipe fix left and right template using c#? Also, it is displaying a gray line above the LLMListView. Can I hide that?

**Comment by brookshi** [comment]
I don't have testing environment for uwp in office, but I think you should not set Template for LLMListViewItem, because swipe is based on this.
I will give you the code that add swipe fix left in C# when I'm back home

**Comment by kinju4374** [comment]
Ok, Thanks.

I want to stretch the LLMListViewItem that's why I was using **ItemContainerStyle**. Right now all the items are not having the same width and also there is progress bar appearing on top of LLMListView. When I see your project it is not appearing. Can you suggest how cam I hide that?

**Comment by brookshi** [comment]
**stretch:**

```
 <llm:LLMListView.ItemContainerStyle>
                        <Style TargetType="llm:LLMListViewItem">
                            <Setter Property="HorizontalContentAlignment" Value="Stretch" />
                        </Style>
                    </llm:LLMListView.ItemContainerStyle>
```

**progressbar** try set CanPullToRefresh  = false

**Comment by kinju4374** [comment]
ok but in your code. You have not set CanPullToRefresh as false. Then also it is hidden. Actually I want pull to refresh also but the progress bar should appear only when user pull to refresh.

**Comment by brookshi** [comment]
I'm home now, below are your questions.
**1. progressbar doesn't hidden**
I need your xaml file to reproduce this issue
**2. add swipe template in C#**
Wait a moment, I'm working for it.

**Comment by brookshi** [comment]
I push the code how to add swipe template in code behind in NormalFixPage.  you can check it.

**Comment by kinju4374** [comment]
Thanks a lot. Also, my XAML is same which I sent before you resolved the Collapsed issue. I have just added an LLMListView inside grid that's it.

**Comment by brookshi** [comment]
in mobile or desktop?

**Comment by kinju4374** [comment]
mobile. And I want to add options inside the DataTemplate using c#, not a just template? Is it possible?

**Comment by brookshi** [comment]
why not use two or more template and set it using c# dynamic?
I find a way to create datatemplate using C#, but event is lost.
Also you can find child and set event in listviewitem's loaded event if you want to take this trouble.

**Comment by brookshi** [comment]
I also can't reproduce the progressbar issue in mobile emulator

**Comment by kinju4374** [comment]
I want add following XAML code dynamically using c#

`<DataTemplate>
                                <Grid Background="Red">
                                    <StackPanel x:Name="RightPanel"
                                                HorizontalAlignment="Right"
                                                Orientation="Horizontal"
                                                VerticalAlignment="Center">
                                        <AppBarButton x:Name="Edit"
                                                      Background="Green"
                                                      Icon="Edit"
                                                      Label="Edit" />
                                        <AppBarButton x:Name="Delete"
                                                      Background="Red"
                                                      Icon="Delete"
                                                      Label="Delete" />
                                    </StackPanel>
                                </Grid>
                            </DataTemplate>`

Also, I have SplitView in my Page and I have added a Grid inside SplitView.Content. and child of Grid is following the element

`<customLV:LLMListView Name="MyListView"
                                          HorizontalAlignment="Stretch"
                                          Visibility="Collapsed"
                                          Grid.Row="1"
                                          ItemRightActionRateForSwipeLength="0.5"
                                          ItemRightSwipeMaxLength="135"
                                          ItemRightSwipeMode="Fix"
                                          ItemContainerStyle="{StaticResource LLMGenericListViewContainerStyle}"
                                          ItemTemplate="{StaticResource MyListTemplate}"
                                          SelectionChanged="MyListView_SelectionChanged">
                        <customLV:LLMListView.ItemRightSwipeContentTemplate>
                            <DataTemplate>
                                <Grid Background="Red">
                                    <StackPanel x:Name="RightPanel"
                                                HorizontalAlignment="Right"
                                                Orientation="Horizontal"
                                                VerticalAlignment="Center">
                                        <AppBarButton x:Name="Edit"
                                                      Background="Green"
                                                      Icon="Edit"
                                                      Label="Edit" />
                                        <AppBarButton x:Name="Delete"
                                                      Background="Red"
                                                      Icon="Delete"
                                                      Label="Delete" />
                                    </StackPanel>
                                </Grid>
                            </DataTemplate>
                        </customLV:LLMListView.ItemRightSwipeContentTemplate>
                    </customLV:LLMListView>`

**Comment by kinju4374** [comment]
Also, could you add the sample code for "I find a way to create datatemplate using C#, but event is lost.
Also you can find child and set event in listviewitem's loaded event if you want to take this trouble." which you mentioned. I will check if I could do something at my side

**Comment by brookshi** [comment]
Pushed! Use command instead of event. you can check it.

**Comment by kinju4374** [comment]
Thanks. Did you replicated that progress bar issue??  Also,  we can use appbarbutton only or we can use other control also. I am asking because my item height is little large and app bar button are displayed very small.

**Comment by brookshi** [comment]
No. I think you can push your code to github

**Comment by kinju4374** [comment]
I found the step to replicate the issue. In NormalFixPage set LLMListView Visibility to Collapsed. After that in PageLoaded event set it Visibility to Visible then it is displayed that progress bar. Even after this steps you are not able to replicate just let me know. I have created a sample project which I will upload on git and send you URL.

**Comment by brookshi** [comment]
OK. thanks. I can reproduce it.

**Comment by kinju4374** [comment]
OK . Is it possible to hide that?

**Comment by brookshi** [comment]
from this url: https://social.msdn.microsoft.com/Forums/en-US/22a0208d-ff10-4393-b80b-8af247199b11/onapplytemplate-not-getting-called-in-my-custom-control-when-visibility-set-to-collapsed?forum=wpf
May need add a property same as ListViewVisibility for this problem, could you tell me why you want to set it to collapse at first

**Comment by kinju4374** [comment]
I have 4 ListView on same page and based on a condition I am displaying particular listview.

**Comment by brookshi** [comment]
How about set collapse in C# code but not in xaml. I try set llmlistview collapse in loaded and then set it to visible, that's ok.

**Comment by kinju4374** [comment]
ok will try it.

**Comment by kinju4374** [comment]
Thanks it is working. But sorry, I am asking one out of box question. Are you aware of any free third party API that displays HTML content, allows formatting options such as Bold,Italic,Underline,etc and then give final output  as HTML?

**Comment by brookshi** [comment]
maybe you can use a web text editer in a webview and interact with it in uwp.

**Comment by kinju4374** [comment]
Are you aware of any sample links?

**Comment by brookshi** [comment]
No, it's just words about my experience. I think it's a practical way

**Comment by kinju4374** [comment]
HI, in that adding DataTemplate dynamically, I don't want to use StringBuilder as the AppBarButton you added are in string that is 2, I am getting list of parameters from my server and then I want to display them dynamically. Is it possible?

**Comment by dnxit** [comment]
Why don't you use the data Templates and then use a TemplateSelector it'll be much more easy

**Comment by brookshi** [comment]
I also want to know why you don't use data template selector

**Comment by kinju4374** [comment]
Yes,but Template Selector will be helpful to select data templates based on some condition. What I want is I want to add content inside DataTemplate dynamically not in XAML. For example right now I am getting 6 options from my server so I want to add those 6 AppBarButton dynamically.

**Comment by brookshi** [comment]
It is hard to know this requirement. How many datatemplate will be created dynamically?

**Comment by kinju4374** [comment]
Can we add content inside DataTemplate dynamically
