### ISSUE TITLE
Disable swipe for some list items based on TemplateSelector 

### ISSUE THREAD

**Issue by dnxit** [brookshi/LLMListView#4]
Is it possible if I want to disable swipe gesture for some specific elements because I'm using TemplateSelector so for some templates I don't need swipe

**Comment by brookshi** [comment]
I add  a event ItemSwipeBeginInTouch, it will be triggered if swipe at beginning.
the only param "sender" is current llmlistviewitem, item's Content is the DataContext. you can set SwipeMode to None for the specific items in the event.
you can checkout code to test it. it's not on nuget now.
please let me know if it can resolve your problem or not.

**Comment by dnxit** [comment]
thanks for your response I'll check it and let you know so that you can put publish to Nuget :+1:

**Comment by brookshi** [comment]
Ok.

**Comment by dnxit** [comment]
In NormalFixPage I've added this event 

```
    private void MasterListView_ItemSwipeBeginInTouch(object sender)
    {
        var ab = sender as LLMListViewItem;
        var a = ab.Content as Contact;
        if(a.Name.Contains("P"))
        {
            MasterListView.ItemRightSwipeMode = SwipeMode.None;
        }
    }
```

I tried it like this based on the condition swipe is enabled for the **first time** and for the **second time** its disabled which is wrong it should not show for the first time as well can you check it

**Comment by brookshi** [comment]
you should set ab.RightSwipeMode = SwipeMode.None

**Comment by dnxit** [comment]
Yes that's working :+1: 
Thank you once again Kindly publish to Nuget now.

**Comment by brookshi** [comment]
Published.

**Comment by dnxit** [comment]
:+1:
