### ISSUE TITLE
Pull to Refresh does not work if Listview is inside Scrollviewer

### ISSUE THREAD

**Issue by dnxit** [brookshi/LLMListView#5]
I'm trying to achieve Pull to Refresh it does not work if my Listview is inside a Scroll viewer can you check it, you can reproduce the issue with the below code I tried it in RefreshButtonPage 

<Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

```
    <ScrollViewer Grid.Row="1" EntranceNavigationTransitionInfo.IsTargetElement="True" Margin="0,4,0,0" ScrollViewer.VerticalScrollBarVisibility="Hidden">
        <StackPanel x:Name="ContentContainer" Margin="0,0,0,0">
            <ctrl:LLMListView x:Name="MasterListView" 
                      ItemsSource="{Binding Contacts, Mode=OneWay}"
                      ItemTemplate="{StaticResource ContactListViewTemplate}" 
                      CanPullToRefresh="True"
                       ItemLeftSwipeMode="None"
                      ItemRightActionRateForSwipeLength="0.5"
                      ItemRightSwipeMaxLength="135"
                      ItemRightSwipeMode="Fix"
                      RefreshButtonVisibility="{x:Bind RefreshBtnVisibility}"
                      IsItemClickEnabled="True"
                      ItemClick="MasterListView_ItemClick">
            </ctrl:LLMListView>
        </StackPanel>
    </ScrollViewer>
</Grid>
```

**Comment by brookshi** [comment]
yes. It's not a good way to add listview in scrollviewer, the scroll event of listview will be invalid.

**Comment by dnxit** [comment]
I've removed the scroll viewer from the xaml now its working fine but scroll some how getting stuck and call the 
lstViewFee.Refresh = async () =>
{
       await Task.Delay(TimeSpan.FromSeconds(3));
       Items.Clear();
       GetFeed().ToList().ForEach(f => Items.Add(f));
       lstViewFee.SetRefresh(false);
}

 ObservableCollection<Feed> _Items = new ObservableCollection<Feed>();
 public ObservableCollection<Feed> Items
 {
       get { return _Items; }
       set { _Items = value; }
}

multiple times to be exactly as many times as many items were in the list.
If I manually scroll a little bit then it stops calling it time and again

**Comment by brookshi** [comment]
Is GetFeed().ToList() a big list?

**Comment by dnxit** [comment]
yes it'll be pulling from server and its gonna be big list
I've multiple templates for multiple types of objects and with a Template selector it picks the right template for the data

**Comment by brookshi** [comment]
GetFeed().ToList().ForEach(f => Items.Add(f));  ObservableCollection Items will update ui for each item. It will block UI thread.
 so you should use List but not ObservableCollection

**Comment by brookshi** [comment]
Or you can use this extended ObservableCollection's AddRange:
https://github.com/brookshi/UWP_ZhiHuRiBao/blob/master/UWP_ZhiHuRiBao/Common/ObservableCollectionExtended.cs

**Comment by dnxit** [comment]
ok I'll use that extended one thanks for your time :+1:

**Comment by dnxit** [comment]
Same behavior with  extended ObservableCollection's AddRange
with simple List its working fine

so how come in your sample its not showing this behavior with Observable collection ???

**Comment by brookshi** [comment]
because it's not a big list. I use extended ObservableCollection's AddRange in my project to improve performance

**Comment by dnxit** [comment]
It'll be good if you could add it in the sample code 
thanks & appreciate your efforts  :+1:
