### ISSUE TITLE
Fixed Right Swip issue in RTL Direction Flow

### ISSUE THREAD

**Issue by dnxit** [brookshi/LLMListView#6]
I'm working on an English/Arabic based app and added Fixed right swipe it works fine when app direction flow is LTR but in RTL swipe is showing on right which is fine but swipe area should be Left not Right in this case so how can I solve it any idea ??

**Comment by brookshi** [comment]
You can set both left swipe template and right swipe template, and set swipe mode dynamicly by language

**Comment by dnxit** [comment]
I've defined both left and right ItemSwipeContentTemplate and I'm setting it like this but its not working

if (cultureName.ToString().Contains("ar"))
            {
                lstEvents.ItemLeftSwipeMode = LLM.SwipeMode.Fix;
                lstEvents.ItemRightSwipeMode = LLM.SwipeMode.None;
                lstEvents.ItemLeftSwipeMaxLength = 135;
                lstEvents.ItemLeftActionRateForSwipeLength = 0.5;
            }
            else
            {
                lstEvents.ItemLeftSwipeMode = LLM.SwipeMode.None;
                lstEvents.ItemRightSwipeMode = LLM.SwipeMode.Fix;
                lstEvents.ItemRightSwipeMaxLength = 135;
                lstEvents.ItemRightActionRateForSwipeLength = 0.5;
            }

**Comment by brookshi** [comment]
try to use converter, 
{Binding CultureName, converter={StaticResource LangToSwipeModeConverter}}

**Comment by afzalgujrat** [comment]
for Arabic it swipe left but shows the Right swipe area and when I release it then it hides the right swipe and show the left swipe under the listview item.
you can see it in the attachment

![untitled](https://cloud.githubusercontent.com/assets/8588638/15673960/2f5a2646-274b-11e6-8e44-b3b58bc17954.png)

**Comment by brookshi** [comment]
please comment your llmlistview code in xaml,  maybe you lose something about converter

**Comment by afzalgujrat** [comment]
Here is my Xaml code 


<ctrl:LLMListView x:Name="lstEvents" 
                                    CanPullToRefresh="True"
                                    ScrollViewer.VerticalScrollBarVisibility="Hidden"
                                    RefreshButtonVisibility="{Binding RefreshBtnVisibility}"
                                    ItemsSource="{Binding Events, Mode=OneWay}"
                                    ItemClick="lstEvents_ItemClick"
                                    IsItemClickEnabled="True"
                                    >
                <ctrl:LLMListView.ItemRightSwipeContentTemplate>
                    <DataTemplate>
                        <Grid Background="#d06f1a">
                            <StackPanel x:Name="RightPanel" HorizontalAlignment="Right" Orientation="Vertical" VerticalAlignment="Stretch">
                                <AppBarButton x:Name="Share" Width="135" Height="80" Label="Share" Click="Share_Click" FontSize="40" Foreground="White" BorderThickness="0,0,0,1" BorderBrush="#FFBA5700">
                                    <AppBarButton.Icon>
                                        <FontIcon FontSize="20" FontFamily="Segoe MDL2 Assets" Glyph="&#xE72D;"/>
                                    </AppBarButton.Icon>
                                </AppBarButton>
                                <AppBarButton x:Name="Apply" Width="135" Height="80" FontFamily="Segeo MDL2 Assets" Label="Apply" Click="Apply_Click" FontSize="40" Foreground="White" BorderThickness="0,1,0,0" BorderBrush="#FFBA5700">
                                    <AppBarButton.Icon>
                                        <FontIcon FontSize="20" FontFamily="Segoe MDL2 Assets" Glyph="&#xE0A2;"/>
                                    </AppBarButton.Icon>
                                </AppBarButton>
                            </StackPanel>
                        </Grid>
                    </DataTemplate>
                </ctrl:LLMListView.ItemRightSwipeContentTemplate>
                <ctrl:LLMListView.ItemLeftSwipeContentTemplate>
                    <DataTemplate>
                        <Grid Background="#d06f1a">
                            <StackPanel x:Name="RightPanel" HorizontalAlignment="Right" Orientation="Vertical" VerticalAlignment="Stretch">
                                <AppBarButton x:Name="Share" Width="135" Height="80" Label="Share" Click="Share_Click" FontSize="40" Foreground="White" BorderThickness="0,0,0,1" BorderBrush="#FFBA5700">
                                    <AppBarButton.Icon>
                                        <FontIcon FontSize="20" FontFamily="Segoe MDL2 Assets" Glyph="&#xE72D;"/>
                                    </AppBarButton.Icon>
                                </AppBarButton>
                                <AppBarButton x:Name="Apply" Width="135" Height="80" FontFamily="Segeo MDL2 Assets" Label="Apply" Click="Apply_Click" FontSize="40" Foreground="White" BorderThickness="0,1,0,0" BorderBrush="#FFBA5700">
                                    <AppBarButton.Icon>
                                        <FontIcon FontSize="20" FontFamily="Segoe MDL2 Assets" Glyph="&#xE0A2;"/>
                                    </AppBarButton.Icon>
                                </AppBarButton>
                            </StackPanel>
                        </Grid>
                    </DataTemplate>
                </ctrl:LLMListView.ItemLeftSwipeContentTemplate>
                <ctrl:LLMListView.ItemTemplate>
                    <DataTemplate x:DataType="data:Event">
                        <Border Margin="0,5" Background="White" BorderBrush="{StaticResource PrimaryBorder}" BorderThickness="0.5" CornerRadius="5">
                            <Grid HorizontalAlignment="Stretch" VerticalAlignment="Stretch">
                                <Grid.RowDefinitions>
                                    <RowDefinition Height="*" />
                                    <RowDefinition Height="3*" />
                                    <RowDefinition Height="*" />
                                </Grid.RowDefinitions>
                                <StackPanel Grid.Row="0" HorizontalAlignment="Stretch">
                                    <Grid Padding="0,0,0,5">
                                        <Grid.RowDefinitions>
                                            <RowDefinition Height="*" />
                                            <RowDefinition Height="*" />
                                        </Grid.RowDefinitions>
                                        <Grid.ColumnDefinitions>
                                            <ColumnDefinition Width="50" />
                                            <ColumnDefinition />
                                            <ColumnDefinition Width="50" />
                                            <ColumnDefinition Width="50" />
                                        </Grid.ColumnDefinitions>

                                        <TextBlock FontSize="30" FontFamily="Segoe MDL2 Assets" Text="&#xE2AD;" Margin="8" Foreground="{StaticResource PrimaryYello}" FontWeight="ExtraBold"/>
                                        <TextBlock Text="Events" x:Uid="lblEvents" Grid.Row="0" Grid.Column="1" HorizontalAlignment="Left" VerticalAlignment="Top" Foreground="{StaticResource PrimaryYello}" FontSize="18" FontFamily="{StaticResource DefaultFont}" Style="{StaticResource BodyTextBlockStyle}" TextWrapping="NoWrap" Margin="10,8,0,0"/>
                                        <TextBlock Text="2 min ago" Grid.Row="0" Grid.Column="1" HorizontalAlignment="Left" VerticalAlignment="Top" Foreground="{StaticResource PrimaryDarkText}" FontSize="8" FontFamily="{StaticResource DefaultFont}" Style="{StaticResource BodyTextBlockStyle}" TextWrapping="NoWrap" Margin="10,30,0,0"/>

                                        <AppBarButton Grid.Column="3" Width="50" Height="50" FontSize="40" Foreground="{StaticResource PrimaryDarkText}">
                                            <AppBarButton.Icon>
                                                <FontIcon FontSize="30" FontFamily="Segoe MDL2 Assets" Glyph="&#xE2B4;"/>
                                            </AppBarButton.Icon>
                                        </AppBarButton>
                                    </Grid>
                                    <Grid>
                                        <Grid.RowDefinitions>
                                            <RowDefinition MaxHeight="60" />
                                            <RowDefinition Height="*" />
                                            <RowDefinition MaxHeight="60" />
                                        </Grid.RowDefinitions>
                                        <Grid.ColumnDefinitions>
                                            <ColumnDefinition Width="*"/>
                                            <ColumnDefinition Width="*"/>
                                            <ColumnDefinition Width="*"/>
                                        </Grid.ColumnDefinitions>

                                        <Image Source="{Binding ImageUrl}" Grid.RowSpan="3" Grid.ColumnSpan="3" Stretch="UniformToFill"/>

                                        <Border CornerRadius="2" Width="65" Height="25" Background="#B200414B" HorizontalAlignment="Left" Margin="5,0,0,0">
                                            <TextBlock Text="{Binding Type}" HorizontalAlignment="Center" Foreground="White"></TextBlock>
                                        </Border>

                                        <Border Grid.ColumnSpan="2" CornerRadius="2" Width="80" Height="25" Background="#B200414B" HorizontalAlignment="Left" Margin="75,0,0,0">
                                            <TextBlock Text="{Binding Category}" HorizontalAlignment="Center" Foreground="White"></TextBlock>
                                        </Border>

                                        <Border CornerRadius="2" Grid.Column="2" Width="80" Height="25" Background="#B2BF7602" HorizontalAlignment="Right" Margin="0,0,5,0">
                                            <TextBlock Text="{Binding Price}" HorizontalAlignment="Center" Foreground="White"></TextBlock>
                                        </Border>

                                        <Grid Grid.Row="4" Grid.ColumnSpan="3" Background="#B200414B">
                                            <Grid.Resources>
                                                <controls:DateFormatConverter x:Key="DateConverter"/>
                                            </Grid.Resources>
                                            <Grid.RowDefinitions>
                                                <RowDefinition MaxHeight="60" />
                                                <RowDefinition Height="*" />
                                            </Grid.RowDefinitions>
                                            <Grid.ColumnDefinitions>
                                                <ColumnDefinition Width="*"/>
                                                <ColumnDefinition Width="*"/>
                                                <ColumnDefinition Width="*"/>
                                            </Grid.ColumnDefinitions>

                                            <TextBlock Text="Start" x:Uid="lblStart" Grid.Row="0" HorizontalAlignment="Left" FontSize="10" Foreground="White" Margin="5,5,0,0"></TextBlock>
                                            <TextBlock Text="End" x:Uid="lblEnd" Grid.Row="0" Grid.Column="2" HorizontalAlignment="Right" FontSize="10" Foreground="White" Margin="0,5,5,0"></TextBlock>

                                            <TextBlock Grid.Row="1" Grid.Column="0" Foreground="White" Text="{Binding StartDate, Converter={StaticResource DateConverter},ConverterParameter=\{0:dd-MMM HH:mm\}}" HorizontalAlignment="Left" Margin="5,0,0,0"></TextBlock>

                                            <Ellipse Grid.Row="1" Grid.Column="1" Width="5" Height="5" Fill="{StaticResource PrimaryYello}" HorizontalAlignment="Left" Margin="5,0,0,0"></Ellipse>
                                            <Rectangle VerticalAlignment="Center" Grid.Row="1" Grid.Column="1" Height="1" Fill="{StaticResource PrimaryYello}" Margin="10,0,10,0" />
                                            <Ellipse Grid.Row="1" Grid.Column="1" Width="5" Height="5" Fill="{StaticResource PrimaryYello}" HorizontalAlignment="Right" Margin="0,0,5,0"></Ellipse>

                                            <TextBlock Grid.Row="1" Grid.Column="2" Foreground="White" Text="{Binding EndDate, Converter={StaticResource DateConverter},ConverterParameter=\{0:dd-MMM HH:mm\}}" HorizontalAlignment="Right" Margin="0,0,5,0"></TextBlock>

                                        </Grid>
                                    </Grid>

                                    <TextBlock Text="{Binding Name}" Margin="15,10,15,5" MaxHeight="80" Foreground="{StaticResource PrimaryDarkText}" FontSize="20" FontFamily="{StaticResource DefaultFont}" TextWrapping="Wrap" TextTrimming="WordEllipsis"/>
                                    <TextBlock Text="{Binding PeopleAttending}" Grid.Row="0" HorizontalAlignment="Left" FontSize="10" Foreground="{StaticResource PrimaryYello}" Margin="15,0,0,10"></TextBlock>
                                </StackPanel>
                            </Grid>
                        </Border>
                    </DataTemplate>
                </ctrl:LLMListView.ItemTemplate>
                <ctrl:LLMListView.ItemContainerStyle>
                    <Style TargetType="ListViewItem">
                        <Setter Property="HorizontalContentAlignment" Value="Stretch"/>
                        <Setter Property="VerticalAlignment" Value="Stretch"/>
                        <Setter Property="Padding" Value="0"/>
                        <Setter Property="Margin" Value="0"/>
                    </Style>
                </ctrl:LLMListView.ItemContainerStyle>
            </ctrl:LLMListView>

**Comment by brookshi** [comment]
I'm not see any converter in the code above. Are you using this way:
if (cultureName.ToString().Contains("ar"))
{
lstEvents.ItemLeftSwipeMode = LLM.SwipeMode.Fix;
lstEvents.ItemRightSwipeMode = LLM.SwipeMode.None;
lstEvents.ItemLeftSwipeMaxLength = 135;
lstEvents.ItemLeftActionRateForSwipeLength = 0.5;
}
else
{
lstEvents.ItemLeftSwipeMode = LLM.SwipeMode.None;
lstEvents.ItemRightSwipeMode = LLM.SwipeMode.Fix;
lstEvents.ItemRightSwipeMaxLength = 135;
lstEvents.ItemRightActionRateForSwipeLength = 0.5;
}

**Comment by afzalgujrat** [comment]
yes its in the page loaded event 

```
private void Page_Loaded(object sender, RoutedEventArgs e)
        {
            var cultureName = new DateTimeFormatter("longdate", new[] { "US" }).ResolvedLanguage;

            if (cultureName.ToString().Contains("ar"))
            {
                lstEvents.ItemLeftSwipeMode = LLM.SwipeMode.Fix;
                lstEvents.ItemRightSwipeMode = LLM.SwipeMode.None;
                lstEvents.ItemLeftSwipeMaxLength = 135;
                lstEvents.ItemLeftActionRateForSwipeLength = 0.5;
            }
            else
            {
                lstEvents.ItemLeftSwipeMode = LLM.SwipeMode.None;
                lstEvents.ItemRightSwipeMode = LLM.SwipeMode.Fix;
                lstEvents.ItemRightSwipeMaxLength = 135;
                lstEvents.ItemRightActionRateForSwipeLength = 0.5;
            }

            this.DataContext = viewModel;
            lstEvents.Refresh = async () =>
            {
                await Task.Delay(TimeSpan.FromSeconds(3));
                viewModel.Events.Clear();
                viewModel.Events = await viewModel.repo.GetAll();
                lstEvents.SetRefresh(false);
            };
        }
```

**Comment by brookshi** [comment]
Do you try this:
use converter, 
ItemLeftSwipeMode =“{Binding CultureName, converter={StaticResource LangToSwipeModeConverter}}”

**Comment by dnxit** [comment]
is LangToSwipeModeConverter available in LLMListview or I've to write that converter ??
but in my opinion I don't think it'll make a difference

**Comment by brookshi** [comment]
you should write it.

**Comment by dnxit** [comment]
I'm unable to figure any solution for this. did you get some time to look into this issue ?

I tried to write a converter and called it like this  but it does not even call this can you check this 

```
<Grid.Resources>
   <controls:DateFormatConverter x:Key="DateConverter"/>
   <controls:LangToSwipeModeConverter x:Key="SwipeModeConverter"/>
</Grid.Resources>

ItemLeftSwipeMode="{Binding CultureName, Converter={StaticResource SwipeModeConverter}}"

public class LangToSwipeModeConverter : IValueConverter
{
        public object Convert(object value, Type targetType, object parameter, string language)
        {
            var a = language;
            return SwipeMode.None;
        }

        public object ConvertBack(object value, Type targetType, object parameter, string language)
        {
            return DependencyProperty.UnsetValue;
        }
}

private string _CultureName = new DateTimeFormatter("longdate", new[] { "US" }).ResolvedLanguage;
public string CultureName
{
       get
       {
             return _CultureName;
       }
       set
       {
            _CultureName = value;
       }
}
```

**Comment by brookshi** [comment]
set a breakpoint at " var a = language;" and debug it. 
will this breakpoint be hit?

**Comment by dnxit** [comment]
no it does not get hit while public string CultureName has the proper value "en-US" or whatever the culture of device will be

**Comment by brookshi** [comment]
Just fancy! I will check it tonight

**Comment by brookshi** [comment]
I add a page named NormalFixPageExtended for this function, you can checkout the code and check it.
Also, it doesn't support dynamic culture in runtime. I think that's ok for language setting.
Culture = "US" for Swipe.Fix and others for Swipe.None

**Comment by dnxit** [comment]
I got the latest and added one line in App.xaml to create my scenario 

```
rootFrame = new Frame();
rootFrame.FlowDirection = FlowDirection.RightToLeft;
```

now you can see the same issue now you'll see the **swiped content on the left** but if you swipe on the **left edge** nothing will happen and if you swipe on the **right edge** then the **fixed content** will be shown on **left side**.

Swipe Left should show Item Left Swipe Content Template
Swipe Right should show Item Right Swipe Content Template

but its showing Item Left swipe content on right swipe gesture which is wrong
it was even doing the same behavior without converter

**Comment by brookshi** [comment]
OK. I think I know what you mean. I will check it tonight

**Comment by brookshi** [comment]
I had set FlowDirection of swipe layer to LeftToRight and add page NormalFixedPageRTL, please check it. Any problem please let me know. Thanks.

**Comment by dnxit** [comment]
In case of RTL Left swipe will be shown instead of right so with this change on NormalFixPageRTL

```
<ctrl:LLMListView x:Name="MasterListView"
                          IsItemClickEnabled="True"
                          ItemLeftActionRateForSwipeLength="0.5"
                          ItemLeftSwipeMaxLength="135"
                          ItemLeftSwipeMode="{Binding Culture,
                                                       Converter={StaticResource LangConverter}}"
                          ItemTemplate="{StaticResource ContactListViewTemplate}"
                          ItemsSource="{x:Bind Contacts, Mode=OneWay}"
                          SelectionMode="Single" />
```

```
private void AddSwipeTemplate()
{
      MasterListView.ItemLeftSwipeContentTemplate = CreateTemplate();
 }
```

see the result in the attached image :( when we release after swipe again showing the swiped content on the **right edge** 

![err](https://cloud.githubusercontent.com/assets/8588638/15883804/c565313c-2d5c-11e6-83f2-3b8227ac190e.png)

**Comment by brookshi** [comment]
I've found the root cause. The issue of left fix swipe existed a long time and I hadn't previously noticed.
I had fixed it and checked in the code. Please check it. Thanks.

**Comment by dnxit** [comment]
I had to change one alignment in the code behind where you're creating swipe template to set the value to Left for the Stack Panel Otherwise working perfect :+1: 

`stringBuilder.Append("<StackPanel HorizontalAlignment=\"Left\" Orientation=\"Horizontal\">");`

I appreciate your efforts and Thank you for your support 
Kindly publish this version to Nuget as well.

**Comment by brookshi** [comment]
Published.
